# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Bren's Blog
email: mail@brennanbrown.ca
description: >- # this means to ignore newlines until "baseurl:"
  A personal journey of lifelong learning,
  sharing resources, creating things, and
  trying to be better.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brennan-archive.netlify.app" # the base hostname & protocol for your site
twitter_username: brennankbrown
github_username: brennanbrown

# SEO metadata
author: "Brennan K. Brown"
twitter:
  username: brennankbrown
  card: summary_large_image
social:
  name: "Brennan K. Brown"
  links:
    - https://brennan-archive.netlify.app
    - https://twitter.com/brennankbrown
    - https://github.com/brennanbrown

paginate: 4
paginate_path: "/page/:num/"
excerpt_separator: <!--more-->

# Build settings

timezone: America/Winnipeg

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Analytics and comments
# Set your GA4 Measurement ID (e.g., G-XXXXXXXXXX) to enable analytics.
ga4_measurement_id: "G-49BH4DQMC2"
disqus_shortname: "brennan-archive"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
